sources:
  trash_bins:
    enabled: true
    sheet_id: '1qFWE4ofT9cA4nz5xQV1ZOD-BMRmr-lzd8Q7howQ3hjY'
    sheet_name: '工作表1'
  toilets:
    enabled: true
    sheet_id: '1yLwmMRjMm_xMgYKn2el17O2P0oB1edZDcgPRxYsIQdc'
    sheet_name: '工作表1'
